# Generated by Django 5.2.4 on 2025-08-08 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='expiry_date',
        ),
    ]
