# Generated by Django 5.2.4 on 2025-08-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=1024)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('logo', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('email', models.EmailField(max_length=254)),
                ('website_link', models.URLField()),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
    ]
